### ISSUE TITLE
First time login link

### ISSUE THREAD

**Issue by d34dman** [MuschPusch/vagrant-aegir#2]
After following the instruction in readme file i was able to complete the installation. But was greeted with username and login screen.

Luckily i had not closed the terminal and was able to retrieve the "first time login link from it"

Maybe it could be mentioned in the doc.

![1__bash](https://f.cloud.github.com/assets/1006481/1966081/1584c87c-82c3-11e3-8906-e9d870f2f143.png)

**Comment by MuschPusch** [comment]
ok done in: https://github.com/MuschPusch/vagrant-aegir/commit/fa041597d269bce87255c9f2e966887ff7614248
