### ISSUE TITLE
Errors in latest development branch

### ISSUE THREAD

**Issue by d34dman** [MuschPusch/vagrant-aegir#5]
Following error shows up in terminal when i try to use `vagrant up` after pulling the latest commits.

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: /Users/rhizom/vagrant/projects/vagrant-aegir

Vagrant:
* Unknown configuration section 'bindfs'.
```

**Comment by d34dman** [comment]
i edited the path to vagrant-aegir to match my local setup and that error got removed.

But the following remains.

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'bindfs'.
```

**Comment by MuschPusch** [comment]
https://github.com/gael-ian/vagrant-bindfs needs to be installed.

**Comment by d34dman** [comment]
thanks, doing `vagrant plugin install vagrant-bindfs` installed the required dependency and everything is right in this world.

**Comment by dancr13** [comment]
answer provided by  @d34dman fixed my problem, thanks.

**Comment by MuschPusch** [comment]
@dbogarin88  this project is abandoned in favor of [multibasebox](https://github.com/factorial-io/multibasebox) I will update the readme asap
